# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
    identifier = "github"
    name       = "GitHub"
    url        = "https://github.com/z3rodol"

    [social.params]
        icon = "brand-github"

[[social]]
    identifier = "twitter"
    name       = "Twitter"
    url        = "https://x.com/z3rodol"

    [social.params]
        icon = "brand-twitter"

[[social]]
    identifier = "linkedin"
    name       = "LinkedIn"
    url        = "https://www.linkedin.com/in/z3rodol"

    [social.params]
        icon = "brand-linkedin"

[[social]]
    identifier = "hackthebox"
    name       = "HacktheBox"
    url        = "https://app.hackthebox.com/public/users/1587799"

    [social.params]
        icon = "brand-hackthebox"